clone:
  git:
    image: 172.24.173.77:30500/woodpecker-git:latest
    settings:
      partial: false
      depth: 1
      # 增加重试次数
      tags: true
steps:
  build-and-push:
    image: 172.24.173.77:30500/standard-docker:latest
    privileged: true
    settings:
      # 这里的配置和 woodpecker 插件完全通用
      registry: http://172.24.173.77:30500
      repo: 172.24.173.77:30500/pr-review
      tags:
        - latest
        - ${CI_COMMIT_SHA:0:7}
      insecure: true
      # 这个插件很简单，不需要 driver_opts
      # 如果需要构建参数：
      build_args:
        - http_proxy=http://172.24.173.76:7899
        - https_proxy=http://172.24.173.76:7899
        - no_proxy=localhost,127.0.0.1,172.24.173.77,10.42.0.0/16,10.43.0.0/16
    when:
      event: [push, tag]
  update-k8s-deployment:
    image: 172.24.173.77:30500/bitnami-kubectl:latest
    environment:
      KUBECONFIG: /woodpecker/kubeconfig
    commands:
      # 【关键】更新 Deployment 的镜像字段
      - kubectl set image deployment/pr-review-service server=172.24.173.77:30500/pr-review:${CI_COMMIT_SHA:0:7} --namespace=default
    when:
      event: [push, tag]
