apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-review-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-review
  template:
    metadata:
      labels:
        app: pr-review
    spec:
      containers:
        - name: server
          image: 172.24.173.77:30500/pr-review:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7995
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          resources:
            requests: # 这种服务非常省资源
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "40Mi"
              cpu: "20m"
      volumes:
        - name: config
          configMap:
            name: pr-review-config
---
apiVersion: v1
kind: Service
metadata:
  name: pr-review-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pr-review
  ports:
    - protocol: TCP
      port: 7995
      targetPort: 7995
      nodePort: 30095
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-review-config
  namespace: default
data:
  config.yaml: |
    # PR Review Service Configuration

    # AI Service URL (required)
    ai_api_url: "http://ai-info-service:3128/chat/completions"

    # AI API Key (required for AI service authentication)
    ai_api_key: "test-api-key"

    # AI Model name (default: qwen-plus-latest)
    ai_model: "qwen-max-latest"

    # Service port (default: 7995)
    port: "7995"

    # GitHub Personal Access Token (required for API access)
    # Needs permissions: repo (for private repos) or public_repo (for public repos)
    github_token: "test-github-token"

    # AI Review Prompts
    # System prompt - defines the AI's role and behavior
    system_prompt: |
      你是一个资深的代码审查专家，拥有 10 年以上的软件开发经验。
      你擅长发现代码中的问题，包括但不限于：Bug、安全漏洞、性能问题、代码规范、最佳实践等。
      请始终保持专业、客观、建设性的态度，用中文回复，使用 Markdown 格式。

    # User prompt template - the actual review request
    # Use {diff} as placeholder for the code diff
    user_prompt_template: |
      审查以下代码变更，Code Review 要点：
      1. **逻辑错误与 Bug**：是否存在潜在的逻辑漏洞、边界条件处理不当或空指针风险？
      2. **代码质量与可读性**：是否遵循 Clean Code 原则？变量命名是否清晰？函数是否过长？是否有冗余代码？
      3. **性能优化**：是否存在不必要的循环、内存泄露或可以优化的算法复杂度？
      4. **安全性**：是否存在常见的安全漏洞（如 SQL 注入、XSS、敏感信息泄露、不安全的加密等）？
      5. **可测试性**：代码是否易于编写单元测试？是否实现了关注点分离？
      6. **最佳实践**：是否符合该编程语言/框架的主流社区最佳实践？
      7. **文档与注释**：是否有必要的注释和文档？注释是否准确反映代码意图？
      8. 如果代码中有写得棒的地方，也请顺带表扬。
      
      用 makrdown 格式，注意下面的括号为输出注意事项，不需要输出，给出简洁的反馈：
    
      ### 评分: 95（打分标准不要输出：满分 100，严重bug<60，有语法错误=0，轻微问题扣5-10分）
      
      ### 修改点:
      - xxxx
      - xxxx
    
      ### 问题:
      （用表格输出。类别为：lint、bug、enhance）
      ｜文件名:行号｜ 严重程度 ｜ 类别｜ 问题描述 ｜ 建议修改
    
      ### 总结: 一句话评价，是否建议合入（建议合入时打✅标记，否则打❌）
    
      ---
      代码变更:
      ```diff
      {diff}
      ```