apiVersion: apps/v1
kind: Deployment
metadata:
  name: pr-review-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pr-review
  template:
    metadata:
      labels:
        app: pr-review
    spec:
      containers:
        - name: server
          image: <你的镜像地址>/pr-review-service:v1 # 替换这里
          imagePullPolicy: IfNotPresent
          env:
            # 指向你的 AI 服务
            - name: AI_API_URL
              value: "http://ai-analyze-service.default.svc.cluster.local:7992/analyze"
          ports:
            - containerPort: 8080
          resources:
            requests: # 这种服务非常省资源
              memory: "20Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: pr-review-service
  namespace: default
spec:
  selector:
    app: pr-review
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080